"""initial sync existing DB

Revision ID: 01c7a3115e18
Revises: 
Create Date: 2025-12-04 10:38:02.286421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c7a3115e18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_record', schema=None) as batch_op:
        batch_op.drop_constraint('task_record_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('website_stats', schema=None) as batch_op:
        batch_op.drop_constraint('website_stats_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('website_stats_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('task_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_record_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
