"""Ajout de colonnes pour l'état de l'ancre et de l'URL

Revision ID: 0446dece7596
Revises: 91cc874aa48d
Create Date: 2023-11-10 17:44:32.554003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0446dece7596'
down_revision = '91cc874aa48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_status', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('anchor_status', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('anchor_status')
        batch_op.drop_column('link_status')

    # ### end Alembic commands ###
