"""Ajout colonne link_follow_status

Revision ID: 05e0816c2c95
Revises: cbee99e5a3c1
Create Date: 2023-11-16 10:25:55.120649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e0816c2c95'
down_revision = 'cbee99e5a3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_follow_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('link_follow_status')

    # ### end Alembic commands ###
