"""Ajout de la date de dernière vérification

Revision ID: 31be91488505
Revises: 0446dece7596
Create Date: 2023-11-11 02:12:48.704129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31be91488505'
down_revision = '0446dece7596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('last_checked')

    # ### end Alembic commands ###
