"""Ajout du champ couleur au modèle Tag

Revision ID: 8ba6baaa1f77
Revises: f62adcfdbcc6
Create Date: 2024-10-30 16:01:40.929273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba6baaa1f77'
down_revision = 'f62adcfdbcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('couleur', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('couleur')

    # ### end Alembic commands ###
