"""empty message

Revision ID: b97f507a69cf
Revises: 0cebce5f58d7
Create Date: 2023-11-13 13:59:08.486755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97f507a69cf'
down_revision = '0cebce5f58d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_plateforme', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('source_plateforme')

    # ### end Alembic commands ###
