"""empty message

Revision ID: cbee99e5a3c1
Revises: da888885b005
Create Date: 2023-11-14 17:49:25.189164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbee99e5a3c1'
down_revision = 'da888885b005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page_trust', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('backlinks_external', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_outlinks_ext', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('num_outlinks_ext')
        batch_op.drop_column('backlinks_external')
        batch_op.drop_column('bas')
        batch_op.drop_column('page_trust')
        batch_op.drop_column('page_value')

    # ### end Alembic commands ###
