"""empty message

Revision ID: da888885b005
Revises: b97f507a69cf
Create Date: 2023-11-14 16:43:11.693999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da888885b005'
down_revision = 'b97f507a69cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_website_user', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_constraint('fk_website_user', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###

