"""Ajout colonne indexe/nonindexe

Revision ID: dec5542627a9
Revises: 05e0816c2c95
Create Date: 2023-11-17 11:21:38.253840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec5542627a9'
down_revision = '05e0816c2c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_index_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website', schema=None) as batch_op:
        batch_op.drop_column('google_index_status')

    # ### end Alembic commands ###
